### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by peplanas** [Maluen/code-medium#1]
Hello, since a few weeks I'm not able to use the extension withing Medium. The icon to add the codes doesn't appears. How can I fix this problem? Thanks.

**Comment by Maluen** [comment]
Confirmed. The extension shows on "New story", but doesn't show when editing existing stories.

**Comment by Maluen** [comment]
Actually it doesn't even always show on "New story".

**Comment by Maluen** [comment]
**Workaround**: reload the editor page and it will show.

**Comment by Maluen** [comment]
Fixed. I published new version 0.2.3 to both Chrome & Firefox web stores.

Should be available shortly. Let me know if you are still experiencing issues.

**Comment by peplanas** [comment]
Thank you!

**Comment by peplanas** [comment]
At Flugel we strive daily to stay up-to-date about technology and best practices We want to share our experience with those who matter to us

At Flugel we strive daily to stay up-to-date about technology and best practices. We want to share our experience with those who matter to us.

Our Experience Working During the COVID19 Pandemic.

mapa-1 (https://hs-5593101.t.hubspotfree.net/e2t/sc2/MmZyHWj__rWW7Ns9qp8fjCn8W5cbnWR6HytWDVWLYGz7q1wXq325P1 )

Working remotely has always been an integral part of our organization, as you may guess, the pandemic hasn't been a problem for our workflow but it has for many others. In this article we share a little of our experience to help companies looking forward to the transition.

Read More
(https://hs-5593101.t.hubspotfree.net/e2t/sc2/MmZyHWj__rWW7Ns9qp8fjCn8W5cbnWR6HytWDVWLYGz7q1wXq3sBq1 )

Learn about the FlugelFlow™ deployment methodology

Flugel-flow (https://hs-5593101.t.hubspotfree.net/e2t/sc2/MmZyHWj__rWW7Ns9qp8fjCn8W5cbnWR6HytWDVWLYGz7q1wXq3V321 )

During our 20+ years of experience migrating, automating, managing, and optimizing cloud infrastructures, we have refined and structured our processes to ensure efficient and effective implementations.  Learn more about  our methodology.

Read More
(https://hs-5593101.t.hubspotfree.net/e2t/sc2/MmZyHWj__rWW7Ns9qp8fjCn8W5cbnWR6HytWDVWLYGz7q1wXq41hxH1 )

Automation is Not ( Only ) About Speed

automation (https://hs-5593101.t.hubspotfree.net/e2t/sc2/MmZyHWj__rWW7Ns9qp8fjCn8W5cbnWR6HytWDVWLYGz7q1wXq41K0j1 )

Everything we do in Flugel.it revolves around infrastructure automation, it is our core business. However, what do we mean by automating infrastructure? Read the article.

Read More
(https://hs-5593101.t.hubspotfree.net/e2t/sc2/MmZyHWj__rWW7Ns9qp8fjCn8W5cbnWR6HytWDVWLYGz7q1wXq426tY1 )

LinkedIn (https://hs-5593101.t.hubspotfree.net/e2t/sc2/MmZyHWj__rWW7Ns9qp8fjCn8W5cbnWR6HytWDVWLYGz7q1wXq42xZz1 )

Twitter (https://hs-5593101.t.hubspotfree.net/e2t/sc2/MmZyHWj__rWW7Ns9qp8fjCn8W5cbnWR6HytWDVWLYGz7q1wXq42Zrb1 )

Website (https://hs-5593101.t.hubspotfree.net/e2t/sc2/MmZyHWj__rWW7Ns9qp8fjCn8W5cbnWR6HytWDVWLYGz7q1wXq43mWR1 )

Flugel.it, 800 Wilshire Blvd, Suite 318, Los Angeles,, California CA90017, United States

Unsubscribe (https://hs-5593101.s.hubspotfree.net/email-unsubscribe/email?product=emailStarter&checkSubscriptions=all&d=Vnzr2p6sWQVxW2p76LK3-1rCSW3M8CY93zgDncW3P1jtn41_3cWW1Y-Pvy41sf2vW49P80r3KbsvFW3R0gmB47TbnlW3JP0gk45RlhdW3P28X24hCPvhW43T2ND8hRhbvW13j25F5N4qjdW5tzC5m6tf81WW4QQRR66S-PHMW6zLkzb6Zd_3ZV1yf0N301Z1FW7QF2Ts7DWFgxN5-lhQsjlXDJ1S3&v=2&email=reply%2Bafuruarkwggcrnzq654san53jrn27evbnhhbyqtkre%40reply.github.com&_hsenc=p2ANqtz-8j67IVfRSeAaHrog_n8GGgNXpWDKa1ZKYu7aC80qDQiJbcana9IltsgIeE0tsGoXwejz-snYnCk43xT4rmZJYmE95soOyg6NrfBAimoPmUQ2tcf1rawhFYdlE5zy9B-HUCD8bGSjiq36jbEePGu-anQVkXvw&_hsmi=93204944 )

Send free email today (https://hs-5593101.t.hubspotfree.net/e2t/sc2/MmZyHWj__rWW7Ns9qp8fjCn8W5cbnWR6HytWDVWLYGz7q1wXq43Pns1 )

HubSpot (https://hs-5593101.t.hubspotfree.net/e2t/sc2/MmZyHWj__rWW7Ns9qp8fjCn8W5cbnWR6HytWDVWLYGz7q1wXq44bT41 )

**Comment by peplanas** [comment]
At Flugel we strive daily to stay up-to-date about technology and best practices We want to share our experience with those who matter to us

At Flugel we strive daily to stay up-to-date about technology and best practices. We want to share our experience with those who matter to us.

Reducing costs by leveraging GKE Optimizations and GCP Preemptible VMs

Pieza_GEK_560x232 (https://hs-5593101.t.hubspotfree.net/e2t/sc2/MmZ-8ykd3XVW8wDVpS5YHJL2W8HGxQC6V_Ct8W2Y1-kr7RbM5WdBzP8M04 )

In this article we will show an example of how the thought process works when we tackle the resource optimization problem. First, let’s address what is Kubernetes: Kubernetes is the world’s most popular container orchestration tool; it’s an open-source system for automating deployment, scaling, and management of containerized applications....

Read More
(https://hs-5593101.t.hubspotfree.net/e2t/sc2/MmZ-8ykd3XVW8wDVpS5YHJL2W8HGxQC6V_Ct8W2Y1-kr7RbM5WdBzP8N04 )

Check out our new video release! Automation Tools.

Pieza_1_560x232 (https://hs-5593101.t.hubspotfree.net/e2t/sc2/MmZ-8ykd3XVW8wDVpS5YHJL2W8HGxQC6V_Ct8W2Y1-kr7RbM5WdBzP8P04 )

Have you heard about automation tools? In this video you can learn why it's so important for today processes when it comes to software development and infrastructure. Check it out.

Watch Video
(https://hs-5593101.t.hubspotfree.net/e2t/sc2/MmZ-8ykd3XVW8wDVpS5YHJL2W8HGxQC6V_Ct8W2Y1-kr7RbM5WdBzP8Q04 )

LinkedIn (https://hs-5593101.t.hubspotfree.net/e2t/sc2/MmZ-8ykd3XVW8wDVpS5YHJL2W8HGxQC6V_Ct8W2Y1-kr7RbM5WdBzP8R04 )

Twitter (https://hs-5593101.t.hubspotfree.net/e2t/sc2/MmZ-8ykd3XVW8wDVpS5YHJL2W8HGxQC6V_Ct8W2Y1-kr7RbM5WdBzP8S04 )

Website (https://hs-5593101.t.hubspotfree.net/e2t/sc2/MmZ-8ykd3XVW8wDVpS5YHJL2W8HGxQC6V_Ct8W2Y1-kr7RbM5WdBzP8T04 )

Flugel.it, 800 Wilshire Blvd, Suite 318, Los Angeles,, California CA90017, United States

Unsubscribe (https://hs-5593101.s.hubspotfree.net/email-unsubscribe/email?product=emailStarter&checkSubscriptions=all&d=VnzSx16sWQVxW2p76LK3-1rCSW3M8CY93zgDncW3P1jtn41_3cWW1Y-Pvy41sf2vW49P80r3KbsvFW3R0gmB47TbnlW3JP0gk45RlhdW3P28X24hCPvhW43T2ND8hRhbvW15gBJz6RmGtTW8VpkVR4YnbXVW4XJRGF4_HKbRVWFCsp98PdY6MXk_7QbvTT_W6HTHd83QQnnQN6V3XFvPHm113jqM2&v=2&email=reply%2Bafuruarkwggcrnzq654san53jrn27evbnhhbyqtkre%40reply.github.com&_hsenc=p2ANqtz--CoTWw71JYrMw4x-nkgzJC4Y1ouGwfFb1h4HgnI80n7XNT5fQKaQpbV-MbH2tbUGSAeavDFBLOEK7r8lHI2_bQNJGr-_dSYwm35Wdlgj55yK_qAKfHyllnaK_fmsVL9ecYyfniC7-XmKkAIHh_20moUmi2Zw&_hsmi=94441879 )

Send free email today (https://hs-5593101.t.hubspotfree.net/e2t/sc2/MmZ-8ykd3XVW8wDVpS5YHJL2W8HGxQC6V_Ct8W2Y1-kr7RbM5WdBzP8V04 )

HubSpot (https://hs-5593101.t.hubspotfree.net/e2t/sc2/MmZ-8ykd3XVW8wDVpS5YHJL2W8HGxQC6V_Ct8W2Y1-kr7RbM5WdBzP8W04 )
