### ISSUE TITLE
Click on the app button causes no action

### ISSUE THREAD

**Issue by e-orlov** [Maluen/code-medium#10]
Extension doesn't work. No any action after clicking on the extension's icon. No errors in the console. Extension is activated, link "options" is deactivated. 
Chrome 97.0.4692.71 x64

**Comment by Maluen** [comment]
The button isn't supposed to do anything. The extension works by extending the medium editor UI. From Features section in README:

>Adds a button in the text toolbar for creating a new Gist and adding it to the post.

See https://www.youtube.com/watch?v=B0UBYV78Cfg on how to use it.
You can also read the article https://medium.com/@Maluen0/how-to-add-code-highlighting-in-medium-articles-without-leaving-the-editor-8f24f5a88d28
