### ISSUE TITLE
Save the Gist when pressing Ctrl + S

### ISSUE THREAD

**Issue by esr360** [Maluen/code-medium#4]
Great plugin, thanks!

It would be quite neat if when editing a Gist, pressing Ctrl + S "saved" the Gist (effectively simulating the "update gist" button).

Medium itself does this when writing an article (pressing Ctrl + S will "save" the article").

Thanks!

**Comment by Maluen** [comment]
Good idea! I'm gonna look into it.

**Comment by Maluen** [comment]
The shortcut is going to work as long as:

- The name, description and code fields aren't empty.
- The gist belongs to the user.
- The focus is on the code-medium window. Meaning it won't work if you click on the left side where the medium artcle is and then click CTRL+S.

Also this only works when updating a gist. We could also add it for new gists, but then it would have to choose between "Create secret gist" and "Create public gist".

Feel free to test this by building the source to provide any feedback or new possible shortcuts. 

I'm going to deploy this to chrome & firefox stores between today and tomorrow.

**Comment by esr360** [comment]
Will just offer some feedback as don't have a chance to test right now.

> Also this only works when updating a gist. We could also add it for new gists, but then it would have to choose between "Create secret gist" and "Create public gist".

Your call on this - I think defaulting to either would be fine, or you could even present the user with an option to choose as default behaviour on first save using localhost or something to save the decision (tbh I have no idea how browser plugins work). Since the gist will be posted in the article perhaps it's a fair assumption that the gist should be public?

Will happily give this a test this weekend.

Thanks again for the great plugin.

**Comment by Maluen** [comment]
Great thinking!

CTRL + S is now also working for creation. It uses "Public" as default. When clicking manually on either "Create secret" or "Create public" buttons, it stores the choice in extension storage and then reuses that next time CTRL + S is pressed.

So basically it remembers the last choice you made.

**Comment by Maluen** [comment]
Published v0.5 to chrome & firefox stores.

Chrome finally reviewed it, so it should be available to everyone now.
